version: '3'
services:
  www:
    image: nginx:alpine
    restart: always
    volumes:
      - /mirrors:/mirrors
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apt-keys:/usr/share/nginx/html/apt-keys
    ports:
      - 8080:80
