version: '3'
services:
  debian-amd64:
    build: ./apt-mirror
    image: apt-mirror:latest
    environment:
      - DEBLINE1=deb-amd64 http://mirrors.aliyun.com/debian stretch main contrib non-free main/debian-installer contrib/debian-installer non-free/debian-installer
      - DEBLINE2=deb-amd64 http://mirrors.aliyun.com/debian-security stretch main contrib non-free
    volumes:
      - /mirrors/debian-x86_64:/mirror
  debian-armhf:
    image: apt-mirror:latest
    environment:
      - DEBLINE1=deb-armhf http://mirrors.tuna.tsinghua.edu.cn/debian stretch main contrib non-free main/debian-installer contrib/debian-installer non-free/debian-installer
      - DEBLINE2=deb-armhf http://mirrors.tuna.tsinghua.edu.cn/debian-security stretch main contrib non-free
    volumes:
      - /mirrors/debian-armhf:/mirror
  debian-docker:
    image: apt-mirror:latest
    environment:
      - DEBLINE=deb-amd64 http://download.docker.com/linux/debian stretch stable
    volumes:
      - /mirrors/debian-docker:/mirror
      - ./gpgs/docker-gpg:/keys/gpg:ro
  pypi:
    build: ./pypi
    image: pypi:latest
    volumes:
      - /mirrors/pypi:/mirror
  elpa:
    build: ./rsync
    image: rsync:latest
    volumes:
      - /mirrors/elpa:/mirror
    environment:
      - UPSTREAM=rsync://elpa.emacs-china.org/elpa/
      - OPTIONS=-avz
  alpine:
    build: ./rsync
    image: rsync:latest
    volumes:
      - /mirrors/alpine:/mirror
    environment:
      - UPSTREAM=rsync://rsync.alpinelinux.org/alpine/
      - OPTIONS=--archive --update --hard-links --delete --delete-after --delay-updates --timeout=600 --exclude=v2.* --exclude=edge --exclude=v3.[0-6] --exclude=aarch64/ --exclude=ppc64le/ --exclude=s390x/ --exclude=x86/ --verbose
