version: '3'
services:
  debian-amd64:
    build: ./apt-mirror
    image: apt-mirror:latest
    restart: always
    environment:
      - UPSTREAM=http://mirrors.aliyun.com/debian
      - RELEASE=stretch
      - ARCH=amd64
    volumes:
      - /mirrors/debian-x86_64:/apt-mirror
  debian-armhf:
    image: apt-mirror:latest
    restart: always
    environment:
      - UPSTREAM=http://mirrors.tuna.tsinghua.edu.cn/debian
      - RELEASE=stretch
      - ARCH=armhf
    volumes:
      - /mirrors/debian-armhf:/apt-mirror
  pypi:
    build: ./pypi
    image: pypi:latest
    restart: always
    volumes:
      - /mirrors/pypi:/pypi
  elpa:
    build: ./elpa
    image: elpa:latest
    restart: always
    volumes:
      - /mirrors/elpa:/elpa
